namespace main_winui {

[default_interface] runtimeclass LayeredFontIcon : Microsoft.UI.Xaml.Controls.FontIcon {
    LayeredFontIcon();

    Windows.Foundation.Collections.IVector<Microsoft.UI.Xaml.Controls.FontIcon>
        FontIcons {
        get;
    };
}

}  // namespace main_winui
