#ifndef LOGIKSIM_VOCABULARY_H
#define LOGIKSIM_VOCABULARY_H

#include "vocabulary/circuit_id.h"
#include "vocabulary/color.h"
#include "vocabulary/connection.h"
#include "vocabulary/connection_count.h"
#include "vocabulary/connection_id.h"
#include "vocabulary/delay.h"
#include "vocabulary/display_state.h"
#include "vocabulary/element_id.h"
#include "vocabulary/element_type.h"
#include "vocabulary/grid.h"
#include "vocabulary/grid_fine.h"
#include "vocabulary/insertion_mode.h"
#include "vocabulary/line.h"
#include "vocabulary/line_fine.h"
#include "vocabulary/logic_small_vector.h"
#include "vocabulary/offset.h"
#include "vocabulary/ordered_line.h"
#include "vocabulary/orientation.h"
#include "vocabulary/part.h"
#include "vocabulary/part_copy_definition.h"
#include "vocabulary/point.h"
#include "vocabulary/point_fine.h"
#include "vocabulary/rect.h"
#include "vocabulary/rect_fine.h"
#include "vocabulary/segment.h"
#include "vocabulary/segment_index.h"
#include "vocabulary/segment_part.h"
#include "vocabulary/time.h"
#include "vocabulary/time_literal.h"
#include "vocabulary/time_rate.h"

#endif
